# Generated by Django 3.0.8 on 2021-12-10 00:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('CompanyId', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Link', models.URLField()),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('DateAdded', models.DateTimeField()),
                ('ContactFirstName', models.CharField(max_length=100)),
                ('ContactLastName', models.CharField(max_length=100)),
                ('ContactPhoneNumber', models.CharField(max_length=100)),
                ('ContactEmail', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
