# Generated by Django 3.0.8 on 2021-12-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='DateAdded',
            field=models.DateField(),
        ),
    ]
