# Generated by Django 3.0.8 on 2021-12-10 00:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211210_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('VacancyId', models.IntegerField()),
                ('PositionName', models.CharField(max_length=100)),
                ('VacancyLink', models.URLField()),
                ('Salary', models.IntegerField()),
                ('Skills', models.CharField(max_length=100)),
                ('MaxExperience', models.IntegerField()),
                ('MinExperience', models.IntegerField()),
                ('CompanyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
