# Generated by Django 3.0.8 on 2021-12-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
