# Generated by Django 3.0.8 on 2021-12-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
