branch-defaults:
  main:
    environment: huntyenv
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: hunty-api3
  branch: null
  default_ec2_keyname: hunty_eb
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
